# Generated by Django 4.0.3 on 2022-04-08 01:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='taggeditem',
            managers=[
                ('objects_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
